#pragma once

enum JoltBroadPhaseLayer : JPH::BroadPhaseLayer::Type {
	GDJOLT_BROAD_PHASE_LAYER_NONE,
	GDJOLT_BROAD_PHASE_LAYER_BODY_STATIC,
	GDJOLT_BROAD_PHASE_LAYER_BODY_MOVING,
	GDJOLT_BROAD_PHASE_LAYER_AREA,
	GDJOLT_BROAD_PHASE_LAYER_MONITOR,
	GDJOLT_BROAD_PHASE_LAYER_AREA_MONITOR,
	GDJOLT_BROAD_PHASE_LAYER_COUNT
};

static_assert(GDJOLT_BROAD_PHASE_LAYER_COUNT <= 8);
