include_guard()

include(GodotJoltExternalLibrary)

set(configurations
	Debug
	RelWithDebInfo
)

GodotJoltExternalLibrary_Add(fmt "${configurations}"
	GIT_REPOSITORY https://github.com/godot-jolt/fmt.git
	GIT_COMMIT a33701196adfad74917046096bf5a2aa0ab0bb50
	OUTPUT_NAME_DEBUG fmtd
	OUTPUT_NAME_RELWITHDEBINFO fmt
	INCLUDE_DIRECTORIES
		<SOURCE_DIR>/include
	CMAKE_CACHE_ARGS
		-DCMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO=${GDJOLT_LTO}
		-DFMT_DOC=FALSE
		-DFMT_INSTALL=FALSE
		-DFMT_TEST=FALSE
	LIBRARY_CONFIG_DEBUG Debug
	LIBRARY_CONFIG_DEVELOPMENT RelWithDebInfo
	LIBRARY_CONFIG_DISTRIBUTION RelWithDebInfo
	LIBRARY_CONFIG_EDITORDEBUG Debug
	LIBRARY_CONFIG_EDITORDEVELOPMENT RelWithDebInfo
	LIBRARY_CONFIG_EDITORDISTRIBUTION RelWithDebInfo
)
