name: 🍎 Build (macOS)
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-12
    name: "\
      ${{ matrix.platform }}-\
      ${{ matrix.editor == true && 'editor-' || '' }}\
      ${{ matrix.config }}"

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-clang]
        editor: [false, true]
        config: [debug, development, distribution]
        version: [14.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup-macos
        with:
          version: ${{ matrix.version }}

      - name: Configure and build
        uses: ./.github/actions/build-with-cmake
        with:
          platform: ${{ matrix.platform }}
          editor: ${{ matrix.editor }}
          config: ${{ matrix.config }}
