name: 🍎 Build (macOS)

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    name: "\
      ${{ matrix.platform }}-\
      ${{ matrix.editor == true && 'editor-' || '' }}\
      ${{ matrix.config }}"

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-clang]
        editor: [false, true]
        config: [debug, development, distribution]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup-macos

      - name: Configure
        uses: ./.github/actions/cmake-configure
        with:
          platform: ${{ matrix.platform }}
        env:
          CXXFLAGS: -Werror

      - name: Build
        uses: ./.github/actions/cmake-build
        with:
          platform: ${{ matrix.platform }}
          editor: ${{ matrix.editor }}
          config: ${{ matrix.config }}
