name: 🕸️ Build (Web)

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  EMSCRIPTEN_VERSION: 3.1.62

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "\
      ${{ matrix.platform }}-\
      ${{ matrix.double == true && 'double-' || '' }}\
      ${{ matrix.editor == true && 'editor-' || '' }}\
      ${{ matrix.config }}"

    strategy:
      fail-fast: true
      matrix:
        platform: [linux-web-wasm32]
        double: [false, true]
        editor: [false, true]
        config: [debug, development, distribution]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
      - name: Verify emsdk
        run: emcc -v

      - name: Configure
        uses: ./.github/actions/cmake-configure
        with:
          strict: true
          platform: ${{ matrix.platform }}
          double: ${{ matrix.double }}
        env:
          CXXFLAGS: -Werror

      - name: Build
        uses: ./.github/actions/cmake-build
        with:
          platform: ${{ matrix.platform }}
          editor: ${{ matrix.editor }}
          config: ${{ matrix.config }}
